### PR TITLE
Update ShutdownHandler.h

### PR DESCRIPTION
**Pull request by pcoscia**
To remove C++11 dependency

### CODE REVIEW

**Comment by james-aurizn** [comment]
Yep good work, my bad with the C++11 syntax.

**Comment by DDominish** [comment]
Hi James,

 

Great to see some movement on LASAGNE.

 

I have two comments:-

 

1.	Whilst I applaud the use of explicit on the cast operator to a bool, it is as noted c++11. Just removing the explicit will work, it can have other unintended implicit conversions (ie. Int/* etc) The original cast operator to a const void * is the most benign conversion that can be used in a conditional statement (ie. If()). A const void * can not be used implicitly to represent anything so that is a common technique to achieve the behaviour. NOTE: My style in these is return (a ? this, 0)
2.	Using NULL is not advisable as it is not always defined (or never used to be) so in such cases use X* = 0 as it uses implicit conversions. This is why throughout ACE it is done this way.

 

Hope this helps

Regards

Derek (0401) 990825

**Review by james-aurizn — DISMISSED** [review]
Only comment I have is that without the explicit guarding the operator bool() it can be a bit dangerous. It might be worth just changing the one usage of the cast in lasagne to explicitly call .has_shutdown()

**Comment by DDominish** [comment]
Hi James

 

It is dangerous to ever cast operator to any integral type..  That is why we use a cast operator (ie operator const void * () const). It will not implicitly cast to anything without explicitly doing so. Go try it  int I = ShutdownHandler(); Also this technique is used in lots of places throughout LASAGNE.  Also your editor does not seem to be inserting spaces…

 

Regards

Derek

**Review by james-aurizn — APPROVED** [review]

**Comment by jwillemsen** [comment]
Maybe merge #145 so that you have more CI builds to test pull requests?

**Pull request merged**
